### ISSUE TITLE
fs.create_directory + all parents

### ISSUE THREAD

**Issue by Julian** [Julian/Filesystems#20]

**Comment by altendky** [comment]
Do you want to modify `fs.create_directory(parents=False)` or add `fs.create_directories()` or...?  Working on this because of https://github.com/Julian/venvs/pull/95/files#r361866720.

**Comment by Julian** [comment]
Since you're gonna need both exists_ok and parents I guess it's fine to do
as flags for now yeah

**Comment by altendky** [comment]
Can be closed after the merge of #47
