### ISSUE TITLE
allow_existing for fs.create_directory()

### ISSUE THREAD

**Issue by altendky** [Julian/Filesystems#48]

**Comment by altendky** [comment]
One situation I got surprised by is that seemingly according to Python's os.makedirs() and bash's mkdir creating a directory for a path which is a symlink to a directory is apparently ok.  I guess we should retain this behavior?

**Comment by Julian** [comment]
My brain hurted parsing that sentence (which I'm sure is Python/bash's fault not yours) but what do you mean?

You mean os.makedirs(some/path/that/is/a/symlink) turns the symlink into a directory?

**Comment by altendky** [comment]
`mkdir -p` doesn't complain when you specify a symlink to a directory.  Neither does `os.makedirs(, exist_ok=True)`.  They both leave it as a symlink.  When I first wrote the applicable tests I wrote them to check for a complaint that the 'directory' already existed.  I was then mildly surprised when I saw they failed.  I then did the tests below, roughly, and found the precedence for not failing when trying to create a directory where a symlink to a directory is present.  Presently I have changed the tests to match the behavior of `mkdir -p` and `os.makedirs(, exist_ok=True)`.

```bash
altendky@p1:/tmp$ rm -rf red blue
altendky@p1:/tmp$ mkdir blue
altendky@p1:/tmp$ ln -s blue red
altendky@p1:/tmp$ ls -dl blue red
drwxrwxr-x 2 altendky altendky 4096 Jan  2 14:39 blue
lrwxrwxrwx 1 altendky altendky    4 Jan  2 14:39 red -> blue
altendky@p1:/tmp$ mkdir -p red
altendky@p1:/tmp$ ls -dl blue red
drwxrwxr-x 2 altendky altendky 4096 Jan  2 14:39 blue
lrwxrwxrwx 1 altendky altendky    4 Jan  2 14:39 red -> blue
altendky@p1:/tmp$ python3.8
Python 3.8.1 (default, Dec 27 2019, 18:45:57) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.makedirs('red', exist_ok=True)
>>>
altendky@p1:/tmp$ ls -dl blue red
drwxrwxr-x 2 altendky altendky 4096 Jan  2 14:39 blue
lrwxrwxrwx 1 altendky altendky    4 Jan  2 14:39 red -> blue
```

For completeness, here is a follow up showing that both of the above fail when the symlink targets a file.  Which would presumably be expected by 'everyone'.

```bash
altendky@p1:/tmp$ touch green
altendky@p1:/tmp$ ln -s green magenta
altendky@p1:/tmp$ ls -dl green magenta
-rw-rw-r-- 1 altendky altendky 0 Jan  2 14:43 green
lrwxrwxrwx 1 altendky altendky 5 Jan  2 14:43 magenta -> green
altendky@p1:/tmp$ mkdir -p magenta
mkdir: cannot create directory ‘magenta’: File exists
altendky@p1:/tmp$ python3.8
Python 3.8.1 (default, Dec 27 2019, 18:45:57) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.makedirs('magenta', exist_ok=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/altendky/.pyenv/versions/3.8.1/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'magenta'
>>> 
altendky@p1:/tmp$ ls -dl green magenta
-rw-rw-r-- 1 altendky altendky 0 Jan  2 14:43 green
lrwxrwxrwx 1 altendky altendky 5 Jan  2 14:43 magenta -> green
```

**Comment by Julian** [comment]
This is done right?
